var BackEndPageJs=new Class.create
BackEndPageJs.prototype=Object.extend(new FrontPageJs,{resultDivId:"",searchDivId:"",totalNoOfItemsId:"",_pagination:{pageNo:1,pageSize:30},_searchCriteria:{},setHTMLIds:function(e,t,a){return this.resultDivId=e,this.searchDivId=t,this.totalNoOfItemsId=a,this},_getNextPageBtn:function(){var e={}
return e.me=this,new Element("tfoot").insert({bottom:new Element("tr").insert({bottom:new Element("td",{colspan:"5","class":"text-center"}).insert({bottom:new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."}).update("Show More").observe("click",function(){e.me._pagination.pageNo=1*e.me._pagination.pageNo+1,jQuery(this).button("loading"),e.me.getResults()})})})})},getSearchCriteria:function(){var e={}
return e.me=this,null===e.me._searchCriteria&&(e.me._searchCriteria={}),e.nothingTosearch=!0,$(e.me.searchDivId).getElementsBySelector("[search_field]").each(function(t){e.me._searchCriteria[t.readAttribute("search_field")]=$F(t),($F(t)instanceof Array&&$F(t).size()>0||"string"==typeof $F(t)&&!$F(t).blank())&&(e.nothingTosearch=!1)}),e.nothingTosearch===!0&&(e.me._searchCriteria=null),this},getBasicVideoEl:function(e,t,a,r){var n={}
return n.me=this,n.width=t||220,n.height=a||180,n.type=r||"video/mp4",n.newDiv=new Element("video",{width:n.width,height:n.height,controls:""}).insert({bottom:new Element("source",{src:e,type:n.type})}).insert({bottom:new Element("span").setStyle("font-weight:bold;").update("Your browser does not support the video tag.")}),n.newDiv},_openNewWindow:function(e){var t={}
return t.me=this,t.newWindow=window.open(e,"New Category","width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no"),t.newWindow.focus(),t.me},_getFormGroup:function(e,t){return new Element("div",{"class":"form-group"}).insert({bottom:e?new Element("label",{"class":"control-label"}).update(e):""}).insert({bottom:t.addClassName("form-control")})},getResults:function(e,t){var a={}
a.me=this,a.reset=e||!1,a.resultDiv=$(a.me.resultDivId),a.reset===!0&&(a.me._pagination.pageNo=1),a.me._pagination.pageSize=t||a.me._pagination.pageSize,a.me.postAjax(a.me.getCallbackId("getItems"),{pagination:a.me._pagination,searchCriteria:a.me._searchCriteria},{onLoading:function(){jQuery("#"+a.me.searchDivId+" #searchBtn").button("loading"),a.reset===!0&&a.resultDiv.update(new Element("tr").update(new Element("td").update(a.me.getLoadingImg())))},onSuccess:function(e,t){try{if(a.result=a.me.getResp(t,!1,!0),!a.result||0==a.result.items.size())return $$(".fa-spin").first().replace(new Element("h4").update("Nothing found")),"Nothing"
$(a.me.totalNoOfItemsId).update(a.result.pageStats.totalRows),a.reset===!0&&a.resultDiv.update(a.me._getResultRow(a.me._getTitleRowData(),!0).wrap(new Element("thead"))),a.resultDiv.getElementsBySelector(".paginWrapper").each(function(e){e.remove()}),a.tbody=$(a.resultDiv).down("tbody"),a.tbody||$(a.resultDiv).insert({bottom:a.tbody=new Element("tbody")}),a.result.items.each(function(e){a.tbody.insert({bottom:a.me._getResultRow(e).addClassName("item_row").writeAttribute("item_id",e.id)})}),a.result.pageStats.pageNumber<a.result.pageStats.totalPages&&a.resultDiv.insert({bottom:a.me._getNextPageBtn().addClassName("paginWrapper")})}catch(r){a.resultDiv.insert({bottom:a.me.getAlertBox("Error",r).addClassName("alert-danger")})}},onComplete:function(){jQuery("#"+a.me.searchDivId+" #searchBtn").button("reset")}})},_saveItem:function(e,t,a){var r={}
return r.me=this,r.data=r.me._collectFormData(t,a),null!==r.data?(r.me.postAjax(r.me.getCallbackId("saveItem"),{item:r.data},{onLoading:function(){r.data.id&&t.addClassName("item_row").writeAttribute("item_id",r.data.id),t.hide()},onSuccess:function(e,a){try{if(r.result=r.me.getResp(a,!1,!0),!r.result||!r.result.item)return
r.row=$(r.me.resultDivId).down("tbody").down(".item_row[item_id="+r.result.item.id+"]"),r.newRow=r.me._getResultRow(r.result.item).addClassName("item_row").writeAttribute("item_id",r.result.item.id),r.row?r.row.replace(r.newRow):($(r.me.resultDivId).down("tbody").insert({top:r.newRow}),t.remove(),$(r.me.totalNoOfItemsId).update(1*$(r.me.totalNoOfItemsId).innerHTML+1))}catch(n){r.me.showModalBox('<span class="text-danger">ERROR:</span>',n,!0),t.show()}}}),r.me):void 0},_collectFormData:function(e,t,a){var r={}
return r.me=this,r.data={},r.hasError=!1,$(e).getElementsBySelector("["+t+"]").each(function(e){r.groupIndexName=a?e.readAttribute(a):null,r.fieldName=e.readAttribute(t),e.hasAttribute("required")&&$F(e).blank()&&(r.me._markFormGroupError(e,"This is requried"),r.hasError=!0),r.itemValue="checkbox"!==e.readAttribute("type")?$F(e):$(e).checked,(e.hasAttribute("validate_currency")||e.hasAttribute("validate_number"))&&(null===r.me.getValueFromCurrency(r.itemValue).match(/^\d+(\.\d{1,2})?$/)&&(r.me._markFormGroupError(e,e.hasAttribute("validate_currency")?e.readAttribute("validate_currency"):e.hasAttribute("validate_number")),r.hasError=!0),r.value=r.me.getValueFromCurrency(r.itemValue)),null!==r.groupIndexName&&void 0!==r.groupIndexName?(r.data[r.groupIndexName]||(r.data[r.groupIndexName]={}),r.data[r.groupIndexName][r.fieldName]=r.itemValue):r.data[r.fieldName]=r.itemValue}),r.hasError===!0?null:r.data},_deactivateItem:function(e){var t={}
t.me=this,t.row=$(e).up("[item_id]"),t.item=t.row.retrieve("data"),t.me.postAjax(t.me.getCallbackId("deactivateItems"),{item_id:t.item.id},{onLoading:function(){t.row&&(t.row.toggleClassName("danger"),t.row.hide())},onSuccess:function(e,a){try{if(t.row.toggleClassName("danger"),t.result=t.me.getResp(a,!1,!0),!t.result.item)throw"errror deactivate item"
t.row.replace(t.me._getResultRow(t.result.item,!1))}catch(r){t.me.showModalBox('<span class="text-danger">ERROR</span>',r,!0)}}})},getLoadingImg:function(){return new Element("i",{"class":"fa fa-refresh fa-spin fa-5x"})}})