var FrontPageJs=new Class.create
FrontPageJs.prototype={resultDivId:"",searchDivId:"",totalNoOfItemsId:"",_pagination:{pageNo:1,pageSize:30},_searchCriteria:{},setHTMLIds:function(e,t,r){return this.resultDivId=e,this.searchDivId=t,this.totalNoOfItemsId=r,this},_getNextPageBtn:function(){var e={}
return e.me=this,new Element("tfoot").insert({bottom:new Element("tr").insert({bottom:new Element("td",{colspan:"5","class":"text-center"}).insert({bottom:new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."}).update("Show More").observe("click",function(){e.me._pagination.pageNo=1*e.me._pagination.pageNo+1,jQuery(this).button("loading"),e.me.getResults()})})})})},getSearchCriteria:function(){var e={}
return e.me=this,null===e.me._searchCriteria&&(e.me._searchCriteria={}),e.nothingTosearch=!0,$(e.me.searchDivId).getElementsBySelector("[search_field]").each(function(t){e.me._searchCriteria[t.readAttribute("search_field")]=$F(t),($F(t)instanceof Array&&$F(t).size()>0||"string"==typeof $F(t)&&!$F(t).blank())&&(e.nothingTosearch=!1)}),e.nothingTosearch===!0&&(e.me._searchCriteria=null),this},getBasicVideoEl:function(e,t,r,a){var n={}
return n.me=this,n.width=t||220,n.height=r||180,n.type=a||"video/mp4",n.newDiv=new Element("video",{width:n.width,height:n.height,controls:""}).insert({bottom:new Element("source",{src:e,type:n.type})}).insert({bottom:new Element("span").setStyle("font-weight:bold;").update("Your browser does not support the video tag.")}),n.newDiv},_openNewWindow:function(e){var t={}
return t.me=this,t.newWindow=window.open(e,"New Category","width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no"),t.newWindow.focus(),t.me},_getFormGroup:function(e,t){return new Element("div",{"class":"form-group"}).insert({bottom:e?new Element("label",{"class":"control-label"}).update(e):""}).insert({bottom:t.addClassName("form-control")})},getResults:function(e,t){var r={}
r.me=this,r.reset=e||!1,r.resultDiv=$(r.me.resultDivId),r.reset===!0&&(r.me._pagination.pageNo=1),r.me._pagination.pageSize=t||r.me._pagination.pageSize,r.me.postAjax(r.me.getCallbackId("getItems"),{pagination:r.me._pagination,searchCriteria:r.me._searchCriteria},{onLoading:function(){jQuery("#"+r.me.searchDivId+" #searchBtn").button("loading"),r.reset===!0&&r.resultDiv.update(new Element("tr").update(new Element("td").update(r.me.getLoadingImg())))},onSuccess:function(e,t){try{if(r.result=r.me.getResp(t,!1,!0),!r.result)return
$(r.me.totalNoOfItemsId).update(r.result.pageStats.totalRows),r.reset===!0&&r.resultDiv.update(r.me._getResultRow(r.me._getTitleRowData(),!0).wrap(new Element("thead"))),r.resultDiv.getElementsBySelector(".paginWrapper").each(function(e){e.remove()}),r.tbody=$(r.resultDiv).down("tbody"),r.tbody||$(r.resultDiv).insert({bottom:r.tbody=new Element("tbody")}),r.result.items.each(function(e){r.tbody.insert({bottom:r.me._getResultRow(e).addClassName("item_row").writeAttribute("item_id",e.id)})}),r.result.pageStats.pageNumber<r.result.pageStats.totalPages&&r.resultDiv.insert({bottom:r.me._getNextPageBtn().addClassName("paginWrapper")})}catch(a){r.resultDiv.insert({bottom:r.me.getAlertBox("Error",a).addClassName("alert-danger")})}},onComplete:function(){jQuery("#"+r.me.searchDivId+" #searchBtn").button("reset")}})},_collectFormData:function(e,t,r){var a={}
return a.me=this,a.data={},a.hasError=!1,$(e).getElementsBySelector("["+t+"]").each(function(e){a.groupIndexName=r?e.readAttribute(r):null,a.fieldName=e.readAttribute(t),e.hasAttribute("required")&&$F(e).blank()&&(a.me._markFormGroupError(e,"This is requried"),a.hasError=!0),a.itemValue="checkbox"!==e.readAttribute("type")?$F(e):$(e).checked,(e.hasAttribute("validate_currency")||e.hasAttribute("validate_number"))&&(null===a.me.getValueFromCurrency(a.itemValue).match(/^\d+(\.\d{1,2})?$/)&&(a.me._markFormGroupError(e,e.hasAttribute("validate_currency")?e.readAttribute("validate_currency"):e.hasAttribute("validate_number")),a.hasError=!0),a.value=a.me.getValueFromCurrency(a.itemValue)),null!==a.groupIndexName&&void 0!==a.groupIndexName?(a.data[a.groupIndexName]||(a.data[a.groupIndexName]={}),a.data[a.groupIndexName][a.fieldName]=a.itemValue):a.data[a.fieldName]=a.itemValue}),a.hasError===!0?null:a.data},getLoadingImg:function(){return new Element("i",{"class":"fa fa-refresh fa-spin fa-5x"})},modalId:"page_modal_box_id",callbackIds:{},initialize:function(){},setCallbackId:function(e,t){return this.callbackIds[e]=t,this},getCallbackId:function(e){if(void 0===this.callbackIds[e]||null===this.callbackIds[e])throw"Callback ID is not set for:"+e
return this.callbackIds[e]},postAjax:function(e,t,r,a){var n={}
return n.request=new Prado.CallbackRequest(e,r),n.request.setCallbackParameter(t),n.timeout=a||3e4,n.timeout<3e4&&(n.timeout=3e4),n.request.setRequestTimeOut(n.timeout),n.request.dispatch(),n.request},getResp:function(e,t,r){var a={}
if(a.expectNonJSONResult=t!==!0?!1:!0,a.result=e,a.expectNonJSONResult===!0)return a.result
if(!a.result.isJSON()){if(a.error="Invalid JSON string: "+a.result,r===!0)throw a.error
return alert(a.error)}if(a.result=a.result.evalJSON(),0!==a.result.errors.size()){if(a.error="Error: \n\n"+a.result.errors.join("\n"),r===!0)throw a.error
return alert(a.error)}return a.result.resultData},getCurrency:function(e,t,r,a,n){var o={}
return o.decimal=isNaN(r=Math.abs(r))?2:r,o.dollar=void 0==t?"$":t,o.decimalPoint=void 0==a?".":a,o.thousandPoint=void 0==n?",":n,o.sign=0>e?"-":"",o.Int=parseInt(e=Math.abs(+e||0).toFixed(o.decimal))+"",o.j=(o.j=o.Int.length)>3?o.j%3:0,o.dollar+o.sign+(o.j?o.Int.substr(0,o.j)+o.thousandPoint:"")+o.Int.substr(o.j).replace(/(\d{3})(?=\d)/g,"$1"+o.thousandPoint)+(o.decimal?o.decimalPoint+Math.abs(e-o.Int).toFixed(o.decimal).slice(2):"")},keydown:function(e,t,r){return e.which&&13==e.which||e.keyCode&&13==e.keyCode?("function"==typeof t&&t(),!1):("function"==typeof r&&r(),!0)},_getErrMsg:function(e){return new Element("span",{"class":"errmsg smalltxt"}).update(e)},getAlertBox:function(e,t){return new Element("div",{"class":"alert alert-dismissible",role:"alert"}).insert({bottom:new Element("button",{"class":"close","data-dismiss":"alert"}).insert({bottom:new Element("span",{"aria-hidden":"true"}).update("&times;")}).insert({bottom:new Element("span",{"class":"sr-only"}).update("Close")})}).insert({bottom:new Element("strong").update(e)}).insert({bottom:t})},_signRandID:function(e){return e.id||(e.id="input_"+String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now()),this},_markFormGroupError:function(e,t){var r={}
return r.me=this,e.up(".form-group")&&(e.up(".form-group").addClassName("has-error"),r.me._signRandID(e),jQuery("#"+e.id).tooltip({trigger:"manual",placement:"auto",container:"body",placement:"bottom",html:!0,title:t}).tooltip("show"),$(e).observe("change",function(){e.up(".form-group").removeClassName("has-error"),jQuery(this).tooltip("hide").tooltip("destroy").show()})),r.me},showModalBox:function(e,t,r,a){var n={}
return n.me=this,n.isSM=r===!0?!0:!1,n.footer=a?a:null,n.newBox=new Element("div",{"class":"modal",tabindex:"-1",role:"dialog","aria-hidden":"true","aria-labelledby":"page-modal-box"}).insert({bottom:new Element("div",{"class":"modal-dialog "+(n.isSM===!0?"modal-sm":"modal-lg")}).insert({bottom:new Element("div",{"class":"modal-content"}).insert({bottom:new Element("div",{"class":"modal-header"}).insert({bottom:new Element("div",{"class":"close",type:"button","data-dismiss":"modal"}).insert({bottom:new Element("span",{"aria-hidden":"true"}).update("&times;")})}).insert({bottom:new Element("strong",{"class":"modal-title",id:"page-modal-box"}).update(e)})}).insert({bottom:new Element("div",{"class":"modal-body"}).update(t)}).insert({bottom:null===n.footer?"":new Element("div",{"class":"modal-footer"}).update(n.footer)})})}),$(n.me.modalId)&&$(n.me.modalId).remove(),$$("body")[0].insert({bottom:n.newBox.writeAttribute("id",n.me.modalId)}),jQuery("#"+n.me.modalId).modal({show:!0,target:"#"+n.me.modalId}),n.me},hideModalBox:function(){var e={}
return e.me=this,jQuery("#"+e.me.modalId).modal("hide"),this},loadUTCTime:function(e){var t={}
return t.strings=e.strip().split(" "),t.dateStrings=t.strings[0].split("-"),t.timeStrings=t.strings[1].split(":"),new Date(Date.UTC(t.dateStrings[0],1*t.dateStrings[1]-1,t.dateStrings[2],t.timeStrings[0],t.timeStrings[1],t.timeStrings[2]))},validateEmail:function(e){var t=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
return t.test(e)},_getLoadingDiv:function(){return new Element("div",{"class":"text-center",style:"padding: 100px 0;"}).insert({bottom:new Element("span",{"class":"fa fa-refresh fa-5x fa-spin"})})}}
